[package]
name = "sway-cheatsheet"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_18"] }
gtk4-layer-shell = "0.5"
clap = { version = "4.0", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
